(function(){'use strict';
const VERSION='5.6.6';
const RACK_MANIFEST='./meal-rack-runtime-manifest-v1.json';
const RACK_PARTS=['./meal-rack-runtime-p1.json','./meal-rack-runtime-p2.json','./meal-rack-runtime-p3.json','./meal-rack-runtime-p4.json','./meal-rack-runtime-p5.json','./meal-rack-runtime-p6.json','./meal-rack-runtime-p7.json','./meal-rack-runtime-p8.json'];
const PLAN_PREFIX='mdp_rack_plan_';
let rack=null,rackError='',rackLoading=null,rackSlot='All',rackQuery='';

const css=`
#dayNav{display:none!important}
.v566-pulse-head{display:flex;align-items:center;justify-content:space-between;gap:10px;margin:-2px 0 12px}
.v566-pulse-title{font-size:9.5px;font-weight:800;letter-spacing:.12em;color:var(--faint)}
.v566-dayctrl{display:flex;align-items:center;gap:4px;margin-left:auto}
.v566-daybtn{width:28px;height:28px;display:grid;place-items:center;background:var(--cardsoft);border:1px solid var(--line);color:var(--muted);border-radius:9px;padding:0;font-size:16px}
.v566-daybtn:disabled{opacity:.28;cursor:default}
.v566-daypill{background:var(--cardsoft);border:1px solid var(--line);color:var(--text);border-radius:10px;padding:6px 9px;min-width:112px;text-align:center;line-height:1.05}
.v566-daypill b{display:block;font-size:11.5px}.v566-daypill small{display:block;font-size:8.5px;color:var(--faint);margin-top:3px;font-weight:600}
.v566-daypill.past{border-color:color-mix(in srgb,var(--turmeric) 65%,var(--line));color:var(--turmeric)}
.v566-rack-card{margin-top:14px!important;border:1px solid color-mix(in srgb,var(--turmeric) 28%,var(--line))}
.v566-rack-head{display:flex;justify-content:space-between;align-items:flex-start;gap:10px}.v566-rack-head h3{font:650 19px/1.1 'Fraunces',Georgia,serif;margin:2px 0 3px}.v566-rack-sub{font-size:10.5px;color:var(--muted);line-height:1.45}.v566-rack-count{white-space:nowrap;font-size:10px;color:var(--turmeric);font-weight:800;background:var(--cardsoft);border:1px solid var(--line);border-radius:999px;padding:5px 8px}
.v566-rack-actions{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:12px}.v566-rack-actions button{width:100%;padding:9px 10px;font-weight:700}
.v566-rack-row{display:flex;align-items:center;gap:9px;border-top:1px solid var(--line);padding:10px 0}.v566-rack-row:first-of-type{margin-top:10px}.v566-rack-main{flex:1;min-width:0}.v566-rack-name{font-size:13px;font-weight:650;line-height:1.25}.v566-rack-meta{font-size:10px;color:var(--muted);margin-top:3px;line-height:1.35}.v566-rack-sugar{font-size:9.5px;color:var(--faint);margin-top:3px}.v566-rack-open{background:none;color:var(--turmeric);font-weight:700;font-size:11px;padding:6px 4px;white-space:nowrap}
.v566-rack-note{font-size:9.5px;color:var(--faint);line-height:1.45;margin-top:9px}.v566-rack-note.warn{color:var(--turmeric)}
.v566-plan-summary{display:grid;grid-template-columns:repeat(3,1fr);gap:6px;margin-top:10px}.v566-plan-stat{background:var(--cardsoft);border-radius:10px;padding:8px;text-align:center}.v566-plan-stat b{display:block;font:650 16px 'Fraunces',Georgia,serif}.v566-plan-stat span{display:block;font-size:8.5px;color:var(--faint);margin-top:2px;text-transform:uppercase;letter-spacing:.04em}
#mealRackSheet{z-index:215}.v566-sheet-head{display:flex;justify-content:space-between;align-items:center;gap:10px}.v566-sheet-head h3{margin:0}.v566-filter{display:flex;gap:6px;overflow-x:auto;padding:10px 0 2px;scrollbar-width:none}.v566-filter::-webkit-scrollbar{display:none}.v566-filter button{white-space:nowrap;background:var(--cardsoft);border:1px solid var(--line);color:var(--muted);border-radius:999px;padding:7px 10px;font-size:10.5px}.v566-filter button.on{background:var(--turmeric);border-color:var(--turmeric);color:#1a1508;font-weight:700}.v566-search{margin-top:10px}.v566-rack-list{margin-top:8px}.v566-detail-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:8px;margin-top:12px}.v566-detail{background:var(--cardsoft);border-radius:12px;padding:10px}.v566-detail b{display:block;font:650 18px 'Fraunces',Georgia,serif}.v566-detail span{display:block;font-size:9px;color:var(--muted);margin-top:3px}.v566-tags{display:flex;gap:6px;flex-wrap:wrap;margin-top:10px}.v566-tag{font-size:9px;border:1px solid var(--line);border-radius:999px;padding:5px 7px;color:var(--muted)}
.v566-today-plan{margin-top:14px}.v566-today-plan .card{margin-top:0}.v566-today-plan-head{display:flex;justify-content:space-between;align-items:center;gap:10px}.v566-today-plan-head strong{font:650 17px 'Fraunces',Georgia,serif}.v566-today-plan-head button{background:none;color:var(--turmeric);font-size:10.5px;font-weight:700;padding:4px}
@media(max-width:365px){.v566-daypill{min-width:100px;padding-left:7px;padding-right:7px}.v566-rack-actions{grid-template-columns:1fr}.v566-plan-summary{grid-template-columns:1fr 1fr 1fr}}
`;
function injectStyle(){if(document.getElementById('v566style'))return;const s=document.createElement('style');s.id='v566style';s.textContent=css;document.head.appendChild(s)}
function read(k,fb){try{const raw=localStorage.getItem(k);return raw?JSON.parse(raw):fb}catch{return fb}}
function write(k,v){try{localStorage.setItem(k,JSON.stringify(v));return true}catch{return false}}
function E(v){return String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')}
function n(v,f=0){const x=Number(v);return Number.isFinite(x)?x:f}
function currentDayKey(){try{return dateKey||todayKey()}catch{return new Date().toISOString().slice(0,10)}}
function todayKeySafe(){try{return todayKey()}catch{const d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}}
function dayNice(k){const d=new Date(k+'T12:00:00');return d.toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric'})}
function isTodayTab(){const t=document.getElementById('tab-today');return !!t&&!t.classList.contains('hide')}
function pulseCard(){return document.getElementById('macroPie')?.closest('.card')||document.querySelector('#tab-today > .card:not(#targetsPanel)')}
function syncPulseDate(){
  const nav=document.getElementById('dayNav');if(nav)nav.style.display='none';
  const card=pulseCard();if(!card)return;let h=document.getElementById('v566PulseHead');if(!h){h=document.createElement('div');h.id='v566PulseHead';h.className='v566-pulse-head';const rings=card.querySelector('.rings');card.insertBefore(h,rings||card.firstChild)}
  const key=currentDayKey(),today=todayKeySafe(),isToday=key===today,label=isToday?`Today · ${new Date(today+'T12:00:00').toLocaleDateString(undefined,{month:'short',day:'numeric'})}`:dayNice(key);
  h.innerHTML=`<div class="v566-pulse-title">DAILY PULSE</div><div class="v566-dayctrl"><button class="v566-daybtn" onclick="goDay(-1)" aria-label="Previous day">‹</button><button class="v566-daypill ${isToday?'':'past'}" ${isToday?'disabled':'onclick="goToday()"'} aria-label="${isToday?'Today':`Viewing ${E(label)}. Return to today`}"><b>${E(label)}</b>${isToday?'':'<small>tap to return to Today</small>'}</button><button class="v566-daybtn" onclick="goDay(1)" ${isToday?'disabled':''} aria-label="Next day">›</button></div>`;
  const dl=document.getElementById('dateLabel');if(dl)dl.style.display=isTodayTab()?'none':'';
}

function inflateRack(x){if(x&&Array.isArray(x.dishes))return x;if(!x||!Array.isArray(x.r)||!Array.isArray(x.c))throw new Error('invalid rack');const bit=(m,a)=>a.filter((_,i)=>(m&(1<<i))!==0);return{recordCount:x.n||x.r.length,status:x.status,sourceRackVersion:x.src,dishes:x.r.map(z=>({id:z[0],base:z[1],v:x.vr[z[2]],name:z[3],cuisine:x.c[z[4]],slots:bit(z[5],x.s),diet:x.d[z[6]],allergens:bit(z[7],x.a),gluten:bit(z[7],x.a).some(a=>a==='gluten'||a==='wheat')?'contains_gluten_or_wheat':'ingredient_dependent',n:{cal:z[8],pro:z[9],carb:z[10],fat:z[11],fiber:z[12],sat:z[13],sugar:z[14],added:z[15],addedStatus:x.as[z[16]]},t:{protein:x.pt[z[17]],fiber:x.ft[z[18]],post:!!z[19],discover:!!z[20]}}))}}
function loadRack(){if(rack)return Promise.resolve(rack);if(rackLoading)return rackLoading;rackLoading=Promise.all([fetch(RACK_MANIFEST,{cache:'force-cache'}).then(r=>{if(!r.ok)throw new Error('rack manifest '+r.status);return r.json()}),...RACK_PARTS.map(u=>fetch(u,{cache:'force-cache'}).then(r=>{if(!r.ok)throw new Error('rack part '+r.status);return r.json()}))]).then(([m,...parts])=>{m.r=parts.flat();rack=inflateRack(m);if(rack.recordCount!==rack.dishes.length)throw new Error('rack count mismatch');rackError='';return rack}).catch(e=>{rackError='Meal rack unavailable';console.warn('Thalify meal rack',e);throw e}).finally(()=>{rackLoading=null});return rackLoading}
function dietAllowed(d){const p=String((typeof profile!=='undefined'&&profile?.diet)||'vegetarian').toLowerCase();const access={vegan:new Set(['vegan']),vegetarian:new Set(['vegan','vegetarian']),eggitarian:new Set(['vegan','vegetarian','eggitarian']),meat:new Set(['vegan','vegetarian','eggitarian','whitemeat']),nonveg:new Set(['vegan','vegetarian','eggitarian','whitemeat']),whitemeat:new Set(['vegan','vegetarian','eggitarian','whitemeat'])};return (access[p]||access.vegetarian).has(d.diet)}
function allergyBlocks(){const s=String((typeof profile!=='undefined'&&profile?.allergies)||'').toLowerCase();const z=new Set();if(!s||/^(none|no|n\/a)$/i.test(s.trim()))return z;const add=(re,...tags)=>{if(re.test(s))tags.forEach(t=>z.add(t))};add(/peanut/,'peanut');add(/tree\s*nut|almond|cashew|walnut|pistach|hazelnut|pecan/,'tree_nut');add(/\bnut(s)?\b/,'tree_nut','peanut');add(/milk|dairy/,'milk');add(/egg/,'egg');add(/soy/,'soy');add(/sesame/,'sesame');add(/fish/,'fish');add(/wheat/,'wheat','gluten');add(/gluten|celiac/,'gluten','wheat');add(/coconut/,'coconut');add(/seed/,'other_seed');return z}
function conflict(d,blocks){if(!blocks.size)return false;return (d.allergens||[]).some(a=>blocks.has(a))||(blocks.has('gluten')&&String(d.gluten).includes('gluten'))}
function cuisinePrefs(){let a=[];try{if(Array.isArray(profile?.cuisines))a=profile.cuisines;else if(profile?.cuisine)a=[profile.cuisine]}catch{}return new Set(a.map(x=>String(x).toLowerCase()))}
function eligible(slot){if(!rack)return[];const blocks=allergyBlocks();return rack.dishes.filter(d=>d.t?.discover!==false&&dietAllowed(d)&&!conflict(d,blocks)&&(!slot||slot==='All'||(d.slots||[]).includes(slot)))}
function sugarText(d){const a=d.n?.added,st=d.n?.addedStatus;if(a==null||st==='unknown')return 'Added sugar unknown';const prefix=st==='estimated'?'~':'';return `${prefix}${Math.round(a*10)/10}g added sugar`}
function prefScore(d){const prefs=cuisinePrefs();return prefs.size&&prefs.has(String(d.cuisine).toLowerCase())?8:0}
function recommendationScore(d,slot){const calT=Math.max(1200,n(typeof targets!=='undefined'&&targets?.cal,2000)),proT=Math.max(40,n(typeof targets!=='undefined'&&targets?.protein,100));const share={Morning:.24,Afternoon:.30,Evening:.32,Other:.14}[slot]||.25,calGoal=calT*share,proGoal=proT*share;let s=100-prefScore(d);s+=Math.abs(n(d.n?.cal)-calGoal)/18;s+=Math.max(0,proGoal-n(d.n?.pro))*1.4;s-=Math.min(n(d.n?.pro),40)*.15;if(d.v==='balanced')s-=2;if(d.t?.protein==='high')s-=3;if(d.t?.fiber==='high')s-=1.5;if(d.n?.added==null)s+=1.5;else s+=Math.max(0,n(d.n.added)-8)*.15;s-=prefScore(d);return s}
function topFor(slot,count=5){return eligible(slot).slice().sort((a,b)=>recommendationScore(a,slot)-recommendationScore(b,slot)).slice(0,count)}
function findDish(id){return rack?.dishes?.find(d=>d.id===id)||null}
function planKey(){return PLAN_PREFIX+currentDayKey()}
function getPlan(){const p=read(planKey(),null);if(!p||!Array.isArray(p.items))return null;return p}
function planTotals(p){let cal=0,pro=0,added=0,known=0;for(const i of p?.items||[]){const d=findDish(i.id);if(!d)continue;cal+=n(d.n?.cal);pro+=n(d.n?.pro);if(d.n?.added!=null){added+=n(d.n.added);known++}}return{cal,pro,added,known,count:(p?.items||[]).length}}
function buildPlan(){
  if(!rack)return null;const slots=['Morning','Afternoon','Evening','Other'],lists=slots.map(s=>topFor(s,8));if(lists.some(a=>!a.length))return null;
  const tCal=Math.max(1200,n(typeof targets!=='undefined'&&targets?.cal,2000)),tPro=Math.max(40,n(typeof targets!=='undefined'&&targets?.protein,100));let best=null,bestScore=1e9;
  for(const a of lists[0])for(const b of lists[1])for(const c of lists[2])for(const d of lists[3]){const arr=[a,b,c,d],ids=new Set(arr.map(x=>x.base)),cuis=new Set(arr.map(x=>x.cuisine));if(ids.size<4)continue;const cal=arr.reduce((s,x)=>s+n(x.n?.cal),0),pro=arr.reduce((s,x)=>s+n(x.n?.pro),0),unknown=arr.filter(x=>x.n?.added==null).length,added=arr.reduce((s,x)=>s+n(x.n?.added,0),0);let sc=Math.abs(cal-tCal)/tCal*110+Math.max(0,tPro-pro)/tPro*150+Math.max(0,pro-tPro*1.35)/tPro*25+unknown*2+added*.08+(4-cuis.size)*2;const prefs=cuisinePrefs();if(prefs.size)sc-=arr.filter(x=>prefs.has(String(x.cuisine).toLowerCase())).length*2;if(sc<bestScore){bestScore=sc;best=arr}}
  if(!best)return null;const p={version:1,date:currentDayKey(),createdAt:Date.now(),targetCalories:tCal,targetProtein:tPro,items:best.map((x,i)=>({slot:slots[i],id:x.id}))};write(planKey(),p);return p
}
function clearPlan(){localStorage.removeItem(planKey())}
function rackRow(d,slot,withOpen=true){return`<div class="v566-rack-row"><div class="v566-rack-main"><div class="v566-rack-name">${E(d.name)}</div><div class="v566-rack-meta">${E(slot||d.slots?.[0]||'Meal')} · ${E(d.cuisine)} · ${Math.round(n(d.n?.cal))} cal · ${Math.round(n(d.n?.pro))}g protein</div><div class="v566-rack-sugar">${E(sugarText(d))} · ${Math.round(n(d.n?.fiber)*10)/10}g fiber</div></div>${withOpen?`<button class="v566-rack-open" onclick="openRackDish('${E(d.id)}')">View ›</button>`:''}</div>`}
function renderPlanSection(p){if(!p)return'';const totals=planTotals(p);return`<div class="v566-plan-summary"><div class="v566-plan-stat"><b>${Math.round(totals.cal)}</b><span>Plan calories</span></div><div class="v566-plan-stat"><b>${Math.round(totals.pro)}g</b><span>Protein</span></div><div class="v566-plan-stat"><b>${totals.known===totals.count?Math.round(totals.added*10)/10+'g':'partial'}</b><span>Added sugar</span></div></div>${p.items.map(i=>{const d=findDish(i.id);return d?rackRow(d,i.slot):''}).join('')}`}
function renderRackCard(){
  const root=document.getElementById('kitchenContent');if(!root)return;let card=document.getElementById('v566RackCard');if(!card){card=document.createElement('div');card.id='v566RackCard';card.className='card v566-rack-card';const hero=root.querySelector('.khero');if(hero)hero.insertAdjacentElement('afterend',card);else root.prepend(card)}
  if(!rack){card.innerHTML=`<div class="v566-rack-head"><div><div class="card-kicker">Meal intelligence</div><h3>Curated meal rack</h3><div class="v566-rack-sub">${rackError||'Loading the reviewed meal library…'}</div></div><span class="v566-rack-count">…</span></div>`;return}
  const p=getPlan(),rec=topFor('Evening',3),blocks=allergyBlocks();card.innerHTML=`<div class="v566-rack-head"><div><div class="card-kicker">Meal intelligence</div><h3>${p?'Your rack plan':'Curated meal rack'}</h3><div class="v566-rack-sub">Profile-aware local planning from the same high-capability rack used by Native.</div></div><span class="v566-rack-count">${rack.recordCount||rack.dishes.length} choices</span></div>${p?renderPlanSection(p):rec.map(d=>rackRow(d,'Recommended')).join('')}<div class="v566-rack-actions"><button class="btn-main" onclick="buildRackDay()">${p?'Refresh day plan':'Build a day'}</button><button class="btn-ghost" onclick="openMealRack()">Browse rack</button></div>${p?'<button class="btn-ghost" style="width:100%;margin-top:8px" onclick="clearRackDay()">Clear rack plan</button>':''}<div class="v566-rack-note ${blocks.size?'warn':''}">${blocks.size?'Known allergen conflicts are excluded, but this rack is still source-binding preview data — verify ingredients before eating.':'Curated nutrition estimates include fiber, saturated fat, total sugar and added sugar. Source binding is still pending, so the rack plans meals but does not count them as eaten.'}</div>`;
}
function renderTodayRackPlan(){const anchor=document.getElementById('planCard');if(!anchor)return;let box=document.getElementById('v566TodayRackPlan');if(!box){box=document.createElement('div');box.id='v566TodayRackPlan';box.className='v566-today-plan';anchor.insertAdjacentElement('afterend',box)}const p=getPlan();if(!p){box.innerHTML='';return}if(!rack){box.innerHTML='';return}const totals=planTotals(p);box.innerHTML=`<div class="card"><div class="v566-today-plan-head"><div><div class="card-kicker">PLANNED FROM MEAL RACK</div><strong>${p.items.length} meals · ${Math.round(totals.cal)} cal · ${Math.round(totals.pro)}g protein</strong></div><button onclick="showTab('kitchen')">Kitchen ›</button></div>${p.items.map(i=>{const d=findDish(i.id);return d?rackRow(d,i.slot,false):''}).join('')}<div class="v566-rack-note">Plan only — meals are not added to your food log until you actually log what you ate.</div></div>`}
function scaffoldSheet(){if(document.getElementById('mealRackSheet'))return;const o=document.createElement('div');o.id='mealRackSheet';o.className='overlay hide';o.setAttribute('role','dialog');o.setAttribute('aria-label','Meal rack');o.innerHTML='<div class="sheet" id="mealRackBody"></div>';document.body.appendChild(o)}
function closeSheet(){document.getElementById('mealRackSheet')?.classList.add('hide')}
function browseRows(){let a=eligible(rackSlot);const q=rackQuery.trim().toLowerCase();if(q)a=a.filter(d=>(d.name+' '+d.cuisine+' '+d.v).toLowerCase().includes(q));return a.sort((x,y)=>recommendationScore(x,rackSlot==='All'?'Evening':rackSlot)-recommendationScore(y,rackSlot==='All'?'Evening':rackSlot)).slice(0,80)}
function renderBrowse(){scaffoldSheet();const body=document.getElementById('mealRackBody');if(!body||!rack)return;const slots=['All','Morning','Afternoon','Evening','Other'],rows=browseRows();body.innerHTML=`<div class="v566-sheet-head"><div><div class="card-kicker">Meal intelligence</div><h3>Browse meal rack</h3></div><button class="btn-ghost" onclick="closeMealRack()">✕</button></div><input class="v566-search" id="v566RackSearch" value="${E(rackQuery)}" placeholder="Search meal or cuisine" oninput="filterMealRack(this.value)"><div class="v566-filter">${slots.map(s=>`<button class="${rackSlot===s?'on':''}" onclick="setRackSlot('${s}')">${s==='Afternoon'?'Midday':s}</button>`).join('')}</div><div class="v566-rack-sub" style="margin-top:8px">Showing ${rows.length} best matches. Diet and known allergy conflicts are filtered locally.</div><div class="v566-rack-list">${rows.map(d=>rackRow(d,d.slots?.[0]||'Meal')).join('')}</div><div class="v566-rack-note">This is the 624-choice runtime projection of the v0.13.0 curated rack. Nutrition remains curated estimate data until source binding is completed.</div>`}
function renderDetail(d){scaffoldSheet();const body=document.getElementById('mealRackBody');if(!body||!d)return;const x=d.n||{},added=x.added==null?'Unknown':`${Math.round(n(x.added)*10)/10} g`;body.innerHTML=`<div class="v566-sheet-head"><button class="btn-ghost" onclick="openMealRack()">← Rack</button><button class="btn-ghost" onclick="closeMealRack()">✕</button></div><div style="margin-top:12px"><div class="card-kicker">${E(d.cuisine)} · ${E(d.v.replace(/_/g,' '))}</div><h3 style="margin:4px 0 0">${E(d.name)}</h3><div class="v566-rack-sub" style="margin-top:6px">${E((d.slots||[]).join(' · '))} · ${E(d.diet)}</div></div><div class="v566-detail-grid"><div class="v566-detail"><b>${Math.round(n(x.cal))}</b><span>Calories</span></div><div class="v566-detail"><b>${Math.round(n(x.pro))}g</b><span>Protein</span></div><div class="v566-detail"><b>${Math.round(n(x.fiber)*10)/10}g</b><span>Fiber</span></div><div class="v566-detail"><b>${Math.round(n(x.sat)*10)/10}g</b><span>Saturated fat</span></div><div class="v566-detail"><b>${Math.round(n(x.sugar)*10)/10}g</b><span>Total sugar</span></div><div class="v566-detail"><b>${E(added)}</b><span>Added sugar</span></div></div><div class="v566-tags"><span class="v566-tag">${E(d.t?.protein||'protein')} protein</span><span class="v566-tag">${E(d.t?.fiber||'fiber')} fiber</span>${(d.allergens||[]).map(a=>`<span class="v566-tag">${E(a.replace(/_/g,' '))}</span>`).join('')}</div><div class="v566-rack-note warn">Planning preview: verify ingredients/allergens. Full ingredient quantities and source IDs are the next source-binding step before production planner approval.</div>`}

window.buildRackDay=async function(){try{await loadRack();const p=buildPlan();renderRackCard();renderTodayRackPlan();if(!p)throw new Error('no plan')}catch(e){console.warn(e);renderRackCard()}};
window.clearRackDay=function(){clearPlan();renderRackCard();renderTodayRackPlan()};
window.openMealRack=async function(){try{await loadRack();rackSlot='All';rackQuery='';renderBrowse();document.getElementById('mealRackSheet').classList.remove('hide')}catch{renderRackCard()}};
window.closeMealRack=closeSheet;
window.setRackSlot=function(s){rackSlot=s;renderBrowse()};
window.filterMealRack=function(v){rackQuery=v;renderBrowse();const i=document.getElementById('v566RackSearch');if(i){i.focus();i.setSelectionRange(i.value.length,i.value.length)}};
window.openRackDish=function(id){const d=findDish(id);if(!d)return;renderDetail(d);document.getElementById('mealRackSheet').classList.remove('hide')};

function enhanceKitchen(){if(!document.getElementById('kitchenContent'))return;renderRackCard()}
function wrap(){
  const oldDay=window.renderDayNav;if(typeof oldDay==='function')window.renderDayNav=function(){const out=oldDay.apply(this,arguments);syncPulseDate();return out};
  const oldRefresh=window.refreshDayView;if(typeof oldRefresh==='function')window.refreshDayView=function(){const out=oldRefresh.apply(this,arguments);syncPulseDate();renderTodayRackPlan();return out};
  const oldTotals=window.renderTotals;if(typeof oldTotals==='function')window.renderTotals=function(){const out=oldTotals.apply(this,arguments);syncPulseDate();renderTodayRackPlan();return out};
  const oldShow=window.showTab;if(typeof oldShow==='function')window.showTab=function(name){const out=oldShow.apply(this,arguments);setTimeout(()=>{const dl=document.getElementById('dateLabel');if(dl)dl.style.display=name==='today'?'none':'';if(name==='today'){syncPulseDate();renderTodayRackPlan()}if(name==='kitchen')enhanceKitchen()},0);return out};
}
injectStyle();scaffoldSheet();wrap();syncPulseDate();loadRack().then(()=>{enhanceKitchen();renderTodayRackPlan()}).catch(()=>{enhanceKitchen()});document.documentElement.dataset.thalifyTwaFeatureRelease=VERSION;
})();
