(function(){'use strict';
const VERSION='5.6.3';
const KEY='mdp_profile_target_settings';
const LB_PER_KG=2.2046226218;
const css=`
.targetcard{padding:0!important;overflow:hidden}.targetcard button{width:100%;background:none;color:var(--text);padding:14px;display:flex;align-items:center;justify-content:space-between;gap:12px;text-align:left}.targetcard .tv{font:600 18px 'Fraunces',Georgia,serif;margin-top:3px}.targetcard .ts{font-size:10.5px;color:var(--faint);margin-top:3px;line-height:1.4}.targetcard .edit{color:var(--turmeric);font-size:11px;font-weight:700;white-space:nowrap}
.targetmodes{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:10px}.targetmodes button{border:1px solid var(--line);background:var(--cardsoft);color:var(--text);padding:10px;border-radius:11px;font-size:11px}.targetmodes button.on{border-color:var(--turmeric);color:var(--turmeric);font-weight:700}.targetfields{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:10px}.targetfields label{font-size:10px;color:var(--muted)}.targetfields input{margin-top:4px}.targethelp{font-size:10.5px;color:var(--muted);line-height:1.5;margin-top:9px}.targetwarn{font-size:10.5px;color:var(--chili);line-height:1.45;margin-top:8px}.targetactions{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:14px}.targetactions button{width:100%}#targetSettingsSheet{z-index:205}
`;
function read(k,fb){try{const raw=localStorage.getItem(k);return raw?JSON.parse(raw):fb}catch{return fb}}
function write(k,v){try{localStorage.setItem(k,JSON.stringify(v));return true}catch{return false}}
function num(v,f=0){const n=Number(v);return Number.isFinite(n)?n:f}
function metric(){return profile?.units==='metric'}
function getSettings(){
  let s=read(KEY,null)||profile?.targetSettings||null;
  const p=profile?.plan||{};
  if(!s){s={mode:'thalify',weeklyMode:'thalify',customCalories:null,customProtein:null,customWeeklyRateKg:null,recommendedCalories:num(p.daily_calories,targets?.cal||0),recommendedProtein:num(p.protein_g,targets?.protein||0),recommendedWeeklyRateKg:num(p.weekly_rate_kg,0)}}
  if(s.mode!=='custom')s.mode='thalify'; if(s.weeklyMode!=='custom')s.weeklyMode='thalify';
  return s;
}
function saveSettings(s){write(KEY,s);try{profile.targetSettings=s;localStorage.setItem('mdp_profile',JSON.stringify(profile))}catch{}}
function rateLabel(kg){const n=metric()?num(kg):num(kg)*LB_PER_KG;const unit=metric()?'kg':'lb';const sign=n>0?'+':'';return `${sign}${n.toFixed(1)} ${unit}/week`}
function ensureSheet(){if(document.getElementById('targetSettingsSheet'))return;const o=document.createElement('div');o.id='targetSettingsSheet';o.className='overlay hide';o.setAttribute('role','dialog');o.setAttribute('aria-label','Nutrition targets');o.innerHTML='<div class="sheet" id="targetSettingsBody"></div>';document.body.appendChild(o)}
function injectStyle(){if(document.getElementById('v563style'))return;const st=document.createElement('style');st.id='v563style';st.textContent=css;document.head.appendChild(st)}
function syncRecommendationSnapshot(){let s=getSettings();if(s.mode==='thalify'){
  const p=profile?.plan||{};s.recommendedCalories=num(p.daily_calories,targets?.cal||s.recommendedCalories);s.recommendedProtein=num(p.protein_g,targets?.protein||s.recommendedProtein);if(s.weeklyMode==='thalify')s.recommendedWeeklyRateKg=num(p.weekly_rate_kg,s.recommendedWeeklyRateKg);saveSettings(s)
}}
function decorateProfile(){const root=document.getElementById('profileContent');if(!root||root.querySelector('.targetcard'))return;const s=getSettings(),p=profile?.plan||{};const cal=num(targets?.cal,p.daily_calories),pro=num(targets?.protein,p.protein_g);const weekly=s.weeklyMode==='custom'?s.customWeeklyRateKg:num(p.weekly_rate_kg,s.recommendedWeeklyRateKg);const d=document.createElement('div');d.className='card targetcard';d.innerHTML=`<button onclick="openTargetSettings()"><span><small style="font-size:9px;color:var(--faint);letter-spacing:.09em;font-weight:800">NUTRITION TARGETS</small><div class="tv">${cal} cal · ${pro}g protein</div><div class="ts">${s.mode==='custom'?'Custom targets':'Thalify recommendation'} · Target trend ${rateLabel(weekly)}</div></span><span class="edit">Edit ›</span></button>`;const cards=root.querySelectorAll('.card');if(cards[0])cards[0].after(d);else root.prepend(d)}
window.closeTargetSettings=()=>document.getElementById('targetSettingsSheet')?.classList.add('hide');
window.setTargetMode=function(mode){const b=document.getElementById('targetSettingsBody');if(!b)return;b.dataset.mode=mode;renderTargetSheet()};
window.setWeeklyTargetMode=function(mode){const b=document.getElementById('targetSettingsBody');if(!b)return;b.dataset.weeklyMode=mode;renderTargetSheet()};
function renderTargetSheet(){ensureSheet();const body=document.getElementById('targetSettingsBody'),s=getSettings();const mode=body.dataset.mode||s.mode,weeklyMode=body.dataset.weeklyMode||s.weeklyMode;const customCal=body.dataset.customCal??s.customCalories??targets?.cal??'';const customPro=body.dataset.customPro??s.customProtein??targets?.protein??'';const rateKg=s.customWeeklyRateKg??num(profile?.plan?.weekly_rate_kg,s.recommendedWeeklyRateKg);const customRate=body.dataset.customRate??(metric()?num(rateKg).toFixed(1):(num(rateKg)*LB_PER_KG).toFixed(1));body.dataset.mode=mode;body.dataset.weeklyMode=weeklyMode;body.innerHTML=`<div class="kshead"><div><div class="card-kicker">Profile</div><h3 style="margin:2px 0 0">Nutrition targets</h3></div><button class="btn-ghost" onclick="closeTargetSettings()">✕</button></div><div class="targethelp">Use Thalify's plan or enter targets from your coach, dietitian or personal program. Profile targets feed Today, Kitchen, Trends and weekly check-ins.</div><div class="ksec">NUTRITION</div><div class="targetmodes"><button class="${mode==='thalify'?'on':''}" onclick="setTargetMode('thalify')">Thalify recommendation</button><button class="${mode==='custom'?'on':''}" onclick="setTargetMode('custom')">My own targets</button></div>${mode==='custom'?`<div class="targetfields"><label>Calories / day<input id="targetCustomCal" inputmode="numeric" value="${customCal}"></label><label>Protein (g)<input id="targetCustomPro" inputmode="numeric" value="${customPro}"></label></div>`:''}<div class="ksec">WEEKLY TARGET</div><div class="targetmodes"><button class="${weeklyMode==='thalify'?'on':''}" onclick="setWeeklyTargetMode('thalify')">Use Thalify goal</button><button class="${weeklyMode==='custom'?'on':''}" onclick="setWeeklyTargetMode('custom')">My coach's target</button></div>${weeklyMode==='custom'?`<label style="display:block;font-size:10px;color:var(--muted);margin-top:10px">Target trend (${metric()?'kg':'lb'} / week)<input id="targetCustomRate" inputmode="decimal" value="${customRate}" style="margin-top:4px"></label><div class="targethelp">Negative = loss, 0 = maintain, positive = gain. This is the intended pace; actual progress is judged from weigh-ins.</div>`:''}<div id="targetSettingsError" class="targetwarn"></div><div class="targetactions"><button class="btn-ghost" onclick="closeTargetSettings()">Cancel</button><button class="btn-main" onclick="saveProfileTargets()">Save targets</button></div>`;
  const ci=document.getElementById('targetCustomCal'),pi=document.getElementById('targetCustomPro'),ri=document.getElementById('targetCustomRate');if(ci)ci.oninput=()=>body.dataset.customCal=ci.value;if(pi)pi.oninput=()=>body.dataset.customPro=pi.value;if(ri)ri.oninput=()=>body.dataset.customRate=ri.value;
}
window.openTargetSettings=function(){ensureSheet();const body=document.getElementById('targetSettingsBody');delete body.dataset.mode;delete body.dataset.weeklyMode;delete body.dataset.customCal;delete body.dataset.customPro;delete body.dataset.customRate;renderTargetSheet();document.getElementById('targetSettingsSheet').classList.remove('hide')};
window.saveProfileTargets=function(){const body=document.getElementById('targetSettingsBody'),s=getSettings(),mode=body.dataset.mode||s.mode,weeklyMode=body.dataset.weeklyMode||s.weeklyMode;const err=document.getElementById('targetSettingsError');let cal=s.customCalories,pro=s.customProtein,rate=s.customWeeklyRateKg;if(mode==='custom'){cal=Math.round(num(document.getElementById('targetCustomCal')?.value,NaN));pro=Math.round(num(document.getElementById('targetCustomPro')?.value,NaN));if(!Number.isFinite(cal)||cal<800||cal>6000||!Number.isFinite(pro)||pro<20||pro>400){if(err)err.textContent='Enter 800–6000 calories and 20–400 g protein.';return}}
  if(weeklyMode==='custom'){let raw=num(document.getElementById('targetCustomRate')?.value,NaN);if(!Number.isFinite(raw)){if(err)err.textContent='Enter a weekly target trend.';return}rate=metric()?raw:raw/LB_PER_KG;if(rate < -1.5 || rate > 1.5){if(err)err.textContent=`Enter a target between ${metric()?'-1.5 and +1.5 kg':'-3.3 and +3.3 lb'} per week.`;return}}
  if(s.mode!=='custom'&&mode==='custom'){s.recommendedCalories=num(targets?.cal,profile?.plan?.daily_calories);s.recommendedProtein=num(targets?.protein,profile?.plan?.protein_g)}if(s.weeklyMode!=='custom'&&weeklyMode==='custom')s.recommendedWeeklyRateKg=num(profile?.plan?.weekly_rate_kg,s.recommendedWeeklyRateKg);
  s.mode=mode;s.weeklyMode=weeklyMode;s.customCalories=cal;s.customProtein=pro;s.customWeeklyRateKg=rate;
  const nextCal=mode==='custom'?cal:num(s.recommendedCalories,targets?.cal),nextPro=mode==='custom'?pro:num(s.recommendedProtein,targets?.protein),nextRate=weeklyMode==='custom'?rate:num(s.recommendedWeeklyRateKg,profile?.plan?.weekly_rate_kg);
  targets={cal:nextCal,protein:nextPro};write('mdp_targets',targets);if(profile?.plan){profile.plan.daily_calories=nextCal;profile.plan.protein_g=nextPro;profile.plan.weekly_rate_kg=nextRate}saveSettings(s);try{localStorage.setItem('mdp_profile',JSON.stringify(profile))}catch{}closeTargetSettings();try{renderTotals()}catch{}try{renderPlanCard()}catch{}try{renderProfile()}catch{}try{if(!document.getElementById('profileFull')?.classList.contains('hide'))renderProfileFull()}catch{}
};
function wrap(){try{const old=renderProfile;renderProfile=function(){old();syncRecommendationSnapshot();decorateProfile()}}catch{}try{const oldApply=window.applyTargets;if(typeof oldApply==='function')window.applyTargets=function(){oldApply();const s=getSettings();if(s.mode==='custom'){s.customCalories=num(targets?.cal,s.customCalories);s.customProtein=num(targets?.protein,s.customProtein)}else{s.recommendedCalories=num(targets?.cal,s.recommendedCalories);s.recommendedProtein=num(targets?.protein,s.recommendedProtein)}saveSettings(s)}}catch{}}
injectStyle();ensureSheet();wrap();try{syncRecommendationSnapshot();decorateProfile()}catch{}document.documentElement.dataset.thalifyTwaFeatureRelease=VERSION;
})();
