(function(){'use strict';
const VERSION='5.6.1';
const P='mdp_kitchen_pantry',G='mdp_kitchen_groceries';
const SYN={spinach:['spinach','palak'],paneer:['paneer'],onion:['onion'],tomato:['tomato'],garlic:['garlic'],yogurt:['yogurt','curd','dahi'],greekyogurt:['greek yogurt'],egg:['egg','eggs'],pepper:['bell pepper','capsicum'],cheese:['cheese'],avocado:['avocado'],bread:['bread','toast'],chickpeas:['chickpea','chana','garbanzo'],rice:['rice'],tofu:['tofu'],broccoli:['broccoli'],soy:['soy sauce'],lentils:['lentil','dal','dhal'],quinoa:['quinoa'],cucumber:['cucumber'],berries:['berry','berries','blueberry','strawberry'],banana:['banana'],chia:['chia']};
const css=`
#checkinResultSheet{align-items:center!important;justify-content:center!important;padding:20px}
#checkinResultSheet>.sheet{border-radius:22px!important;max-width:448px;max-height:min(82vh,680px);padding:22px 18px calc(22px + env(safe-area-inset-bottom));box-shadow:0 22px 70px rgba(0,0,0,.36)}
.kchips button.kselected,.kgchips button.kselected{background:var(--turmeric)!important;border-color:var(--turmeric)!important;color:#1a1508!important;font-weight:700}
.kgrocery-link{background:var(--cardsoft);border:1px solid var(--line);color:var(--turmeric);padding:5px 8px;border-radius:999px;font-size:9.5px;font-weight:700;white-space:nowrap}
.kgrocery-link.done{color:var(--leaf)}
.kgroceryplus{width:32px!important;height:32px!important;font-size:19px!important;flex:0 0 32px;margin-left:8px}
.kux-status{margin-top:10px;background:color-mix(in srgb,var(--leaf) 10%,var(--cardsoft));border:1px solid color-mix(in srgb,var(--leaf) 45%,var(--line));border-radius:10px;padding:8px 10px;font-size:11px;color:var(--text);line-height:1.4}
.kgchips{display:flex;gap:6px;flex-wrap:wrap}.kgchips button{background:var(--cardsoft);border:1px solid var(--line);color:var(--text);padding:7px 10px;border-radius:999px;font-size:11px}
.kitchen-toast{position:fixed;left:50%;bottom:calc(88px + env(safe-area-inset-bottom));transform:translate(-50%,10px);z-index:260;background:var(--text);color:var(--bg);border-radius:999px;padding:9px 14px;font-size:11.5px;font-weight:700;opacity:0;pointer-events:none;transition:opacity .18s,transform .18s;max-width:min(88vw,420px);text-align:center;box-shadow:0 8px 30px rgba(0,0,0,.25)}
.kitchen-toast.show{opacity:1;transform:translate(-50%,0)}
@media(max-width:520px){#checkinResultSheet{padding:16px}#checkinResultSheet>.sheet{width:min(100%,448px);border-radius:20px!important}}
`;
function injectStyle(){if(document.getElementById('v561style'))return;const s=document.createElement('style');s.id='v561style';s.textContent=css;document.head.appendChild(s)}
function read(k,fb){try{const v=localStorage.getItem(k);return v?JSON.parse(v):fb}catch{return fb}}
function write(k,v){try{localStorage.setItem(k,JSON.stringify(v));return true}catch{return false}}
function clean(v){return String(v||'').replace(/^\s*✓\s*/,'').trim()}
function canon(v){let s=clean(v).toLowerCase(),all=[];for(const [k,a] of Object.entries(SYN))for(const q of a)all.push([k,q]);all.sort((a,b)=>b[1].length-a[1].length);for(const [k,q] of all)if(s.includes(q))return k;return s.trim().replace(/\s+/g,'-')}
function pantry(){return read(P,[])}function groceries(){return read(G,[])}
function pantryItemForName(name){const k=canon(name);return pantry().find(x=>x.k===k||canon(x.n)===k)||null}
function groceryForPantry(item){if(!item)return null;return groceries().find(g=>!g.done&&(g.sourcePantryId===item.id||g.k===item.k||canon(g.n)===item.k))||null}
function kitchenVisible(){const t=document.getElementById('tab-kitchen');return !!t&&!t.classList.contains('hide')}
function toast(msg){let t=document.getElementById('kitchenUxToast');if(!t){t=document.createElement('div');t.id='kitchenUxToast';t.className='kitchen-toast';document.body.appendChild(t)}t.textContent=msg;t.classList.add('show');clearTimeout(window._kitchenUxToastTimer);window._kitchenUxToastTimer=setTimeout(()=>t.classList.remove('show'),1700)}
function sheetStatus(msg){const body=document.getElementById('kitchenSheetBody');if(!body)return;let s=document.getElementById('kuxSheetStatus');if(!s){s=document.createElement('div');s.id='kuxSheetStatus';s.className='kux-status';const input=body.querySelector('input');const anchor=input?.nextElementSibling||body.querySelector('.kshead');if(anchor)anchor.insertAdjacentElement('afterend',s);else body.appendChild(s)}s.textContent=msg}
function decorateQuickPantry(){const body=document.getElementById('kitchenSheetBody');if(!body)return;const names=new Set(pantry().map(x=>x.k||canon(x.n)));body.querySelectorAll('.kchips button').forEach(b=>{const base=clean(b.textContent);const selected=names.has(canon(base));b.classList.toggle('kselected',selected);b.setAttribute('aria-pressed',selected?'true':'false');b.textContent=(selected?'✓ ':'')+base})}
function decorateQuickGroceries(){const body=document.getElementById('kitchenSheetBody');if(!body)return;const pending=new Set(groceries().filter(x=>!x.done).map(x=>x.k||canon(x.n)));body.querySelectorAll('.kgchips button').forEach(b=>{const base=clean(b.textContent);const selected=pending.has(canon(base));b.classList.toggle('kselected',selected);b.setAttribute('aria-pressed',selected?'true':'false');b.textContent=(selected?'✓ ':'')+base})}
function addGrocery(name,sourcePantryId){name=clean(name);if(!name)return{added:false};const k=canon(name),a=groceries();let x=a.find(g=>g.k===k||canon(g.n)===k);const p=sourcePantryId?pantry().find(i=>i.id===sourcePantryId):pantryItemForName(name);const linkedId=sourcePantryId||(p&&p.low?p.id:null);if(x){const wasPending=!x.done;x.done=false;x.n=name;x.k=k;if(linkedId){x.sourcePantryId=linkedId;x.source='pantry'}write(G,a);return{added:!wasPending,item:x}}x={id:'gux'+Date.now()+Math.random().toString(36).slice(2,7),k,n:name,done:false,source:linkedId?'pantry':'direct'};if(linkedId)x.sourcePantryId=linkedId;a.push(x);write(G,a);return{added:true,item:x}}
function refreshKitchen(){if(kitchenVisible()&&typeof window.showTab==='function')window.showTab('kitchen');else setTimeout(enhanceKitchenDom,0)}
function enhanceKitchenDom(){if(!kitchenVisible())return;const root=document.getElementById('kitchenContent');if(!root)return;const cards=[...root.querySelectorAll('.kcard')];const pantryCard=cards.find(c=>c.querySelector('.serif')?.textContent.trim()==='Pantry');if(pantryCard){const ps=pantry();pantryCard.querySelectorAll('.krow').forEach(row=>{row.querySelector('.kgrocery-link')?.remove();const name=row.querySelector('span')?.textContent.trim(),state=row.querySelector('.kstate');if(!name||!state||state.textContent.trim()!=='Low')return;const item=ps.find(x=>canon(x.n)===canon(name));if(!item)return;const ing=groceryForPantry(item),b=document.createElement('button');b.type='button';b.className='kgrocery-link'+(ing?' done':'');b.textContent=ing?'In groceries ✓':'+ Grocery';b.setAttribute('aria-label',ing?`${name} is in groceries`:`Add ${name} to groceries`);b.onclick=()=>window.addPantryToGroceries(item.id);const x=row.querySelector('.kx');row.insertBefore(b,x||null)})}
const groceryCard=cards.find(c=>c.querySelector('.kcollapse b')?.textContent.trim()==='Groceries');if(groceryCard){const head=groceryCard.querySelector('.kcollapse');if(head&&!head.querySelector('.kgroceryplus')){const b=document.createElement('button');b.type='button';b.className='kplus kgroceryplus';b.textContent='+';b.setAttribute('aria-label','Add grocery item');b.onclick=window.openGroceryAdd;head.appendChild(b)}}}
window.addPantryToGroceries=function(id){const p=pantry(),item=p.find(x=>x.id===id);if(!item)return;const r=addGrocery(item.n,item.id);refreshKitchen();toast(r.added?`✓ ${item.n} added to Groceries`:`${item.n} is already in Groceries`)};
window.openGroceryAdd=function(){const body=document.getElementById('kitchenSheetBody'),sheet=document.getElementById('kitchenSheet');if(!body||!sheet)return;const low=pantry().filter(x=>x.low&&!groceryForPantry(x)),common=['Bananas','Milk','Bread','Tomatoes','Eggs','Yogurt','Spinach','Onion'];body.innerHTML=`<div class="kshead"><h3 style="margin:0">Add grocery</h3><button class="btn-ghost" onclick="closeKitchenSheet()">✕</button></div><input id="kginput" style="margin-top:12px" placeholder="What do you need?"><button class="btn-main" style="width:100%;margin-top:9px" onclick="addGroceryDirect()">Add to groceries</button>${low.length?`<div class="ksec">LOW IN YOUR PANTRY</div><div class="kgchips">${low.map(x=>`<button onclick="quickGroceryFromPantry('${x.id}')">${clean(x.n)}</button>`).join('')}</div>`:''}<div class="ksec">RECENT / COMMON</div><div class="kgchips">${common.map(x=>`<button onclick="quickGrocery('${x}')">${x}</button>`).join('')}</div>`;sheet.classList.remove('hide');decorateQuickGroceries();setTimeout(()=>document.getElementById('kginput')?.focus(),50)};
window.addGroceryDirect=function(){const i=document.getElementById('kginput'),v=clean(i?.value);if(!v)return;const r=addGrocery(v);sheetStatus(r.added?`✓ ${v} added to Groceries`:`${v} is already in Groceries`);if(i){i.value='';i.focus()}decorateQuickGroceries();refreshKitchen()};
window.quickGrocery=function(v){const r=addGrocery(v);sheetStatus(r.added?`✓ ${v} added to Groceries`:`${v} is already in Groceries`);decorateQuickGroceries();refreshKitchen()};
window.quickGroceryFromPantry=function(id){const item=pantry().find(x=>x.id===id);if(!item)return;const r=addGrocery(item.n,item.id);sheetStatus(r.added?`✓ ${item.n} added to Groceries`:`${item.n} is already in Groceries`);decorateQuickGroceries();refreshKitchen()};
function wrapExisting(){const oldOpen=window.openPantryAdd;if(typeof oldOpen==='function')window.openPantryAdd=function(){oldOpen();setTimeout(decorateQuickPantry,0)};
const oldQuick=window.quickPantry;if(typeof oldQuick==='function')window.quickPantry=function(v){const existed=!!pantryItemForName(v);oldQuick(v);decorateQuickPantry();sheetStatus(existed?`${clean(v)} is already in Pantry · marked Have`:`✓ ${clean(v)} added to Pantry`);setTimeout(enhanceKitchenDom,0)};
const oldAdd=window.addPantry;if(typeof oldAdd==='function')window.addPantry=function(){const i=document.getElementById('kpinput'),v=clean(i?.value),existed=v?!!pantryItemForName(v):false;oldAdd();if(v)sheetStatus(existed?`${v} is already in Pantry · marked Have`:`✓ ${v} added to Pantry`);decorateQuickPantry();setTimeout(enhanceKitchenDom,0)};
const oldToggle=window.togglePantry;if(typeof oldToggle==='function')window.togglePantry=function(id){oldToggle(id);setTimeout(enhanceKitchenDom,0)};
const oldRemove=window.removePantry;if(typeof oldRemove==='function')window.removePantry=function(id){oldRemove(id);setTimeout(enhanceKitchenDom,0)};
const oldToggleG=window.toggleGrocery;if(typeof oldToggleG==='function')window.toggleGrocery=function(id){oldToggleG(id);const g=groceries().find(x=>x.id===id);if(g?.done&&g.sourcePantryId){const a=pantry(),p=a.find(x=>x.id===g.sourcePantryId);if(p&&p.low){p.low=false;write(P,a);toast(`✓ ${p.n} restocked in Pantry`);refreshKitchen();return}}setTimeout(enhanceKitchenDom,0)};
const oldRemoveG=window.removeGrocery;if(typeof oldRemoveG==='function')window.removeGrocery=function(id){oldRemoveG(id);setTimeout(enhanceKitchenDom,0)};
const oldShow=window.showTab;if(typeof oldShow==='function')window.showTab=function(n){oldShow(n);if(n==='kitchen')setTimeout(enhanceKitchenDom,0)};
}
injectStyle();wrapExisting();if(kitchenVisible())setTimeout(enhanceKitchenDom,0);document.documentElement.dataset.thalifyTwaFeatureRelease=VERSION;
})();
