(function(){'use strict';
const V='5.6.14',K='mdp_meal_packs_v1';let S=null;
const C=`#mealPackPage{z-index:165}.mpc{background:var(--card);border:1px solid var(--line);border-radius:16px;padding:13px;margin-bottom:9px}.mpr{display:flex;gap:7px;align-items:center;flex-wrap:wrap}.mpb{background:var(--turmeric);color:#171205;padding:8px 12px;font-weight:700;border-radius:9px}.mpg{background:var(--cardsoft);color:var(--text);border:1px solid var(--line);padding:8px 11px;border-radius:9px}.mpq{background:none;color:var(--muted);border:1px solid var(--line);padding:7px 9px;border-radius:9px}.mpd{background:none;color:var(--chili);border:1px solid var(--line);padding:7px 9px;border-radius:9px}.mpn{font-size:15px;font-weight:750}.mpm{font-size:10.5px;color:var(--muted);margin-top:3px;line-height:1.4}.mpi{font-size:11px;color:var(--muted);margin:8px 0;line-height:1.4}.mpx{display:grid;grid-template-columns:auto 1fr auto;gap:8px;align-items:center}.mpx+.mpx{margin-top:7px}.mpx input[type=checkbox]{width:18px;height:18px}.mps{display:flex;gap:4px;align-items:center}.mps button{width:28px;height:28px;background:var(--cardsoft);color:var(--text);border:1px solid var(--line)}.mpt{font-size:11px;font-weight:700;min-width:38px;text-align:center}.mpf{display:grid;grid-template-columns:1fr 130px;gap:8px;margin-bottom:10px}.mpf input,.mpf select{background:var(--cardsoft)}.mpit{display:grid;grid-template-columns:1fr 74px auto;gap:7px;align-items:center;padding:8px 0;border-bottom:1px solid var(--line)}.mpit input{padding:7px!important;background:var(--cardsoft)!important}.mp-tools{display:flex;gap:6px;justify-content:flex-end;margin:-2px 0 9px}.mp-tools button{background:none;border:1px solid var(--line);color:var(--muted);font-size:10px;padding:5px 7px}.mp-tools button:first-child{color:var(--turmeric)}.mpres button{display:flex;width:100%;gap:8px;justify-content:space-between;background:none;color:var(--text);border-bottom:1px solid var(--line);padding:8px 2px;text-align:left}.mpres small{color:var(--muted)}@media(max-width:390px){.mpf{grid-template-columns:1fr}.mpx{grid-template-columns:auto 1fr}.mps{grid-column:2}.mpit{grid-template-columns:1fr auto}.mpit input{grid-row:2;grid-column:1}}`;
function e(v){return String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\"/g,'&quot;').replace(/'/g,'&#39;')}
function rd(){try{let a=JSON.parse(localStorage.getItem(K)||'[]');return Array.isArray(a)?a:[]}catch{return[]}}
function wr(a){localStorage.setItem(K,JSON.stringify(a));tile();decor();}
function id(){return'mp_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,6)}
function ms(){try{return MEALS}catch{return['Morning','Afternoon','Evening','Other']}}
function mac(n,c,p,cb,f){if(cb!=null&&f!=null)return{carbs:+cb||0,fat:+f||0};try{return estimateMacros(n,+c||0,+p||0)}catch{return{carbs:0,fat:0}}}
function snap(x){let n=String(x.name||'Food');try{n=normalizeSpecialPortionName(n)}catch{}let m=mac(n,x.cal,x.protein,x.carbs,x.fat);return{name:n,cal:+x.cal||0,protein:+x.protein||0,carbs:+m.carbs||0,fat:+m.fat||0,qty:Math.max(.25,Math.min(10,+x.qty||1))}}
function mi(m){try{return log.filter(x=>x.meal===m).map(snap)}catch{return[]}}
function tot(a){return a.reduce((z,x)=>(z.c+=x.cal*(x.qty||1),z.p+=x.protein*(x.qty||1),z),{c:0,p:0})}
function gp(x){return rd().find(p=>p.id===x)}
function put(p){let a=rd(),i=a.findIndex(x=>x.id===p.id);i<0?a.push(p):a[i]=p;wr(a)}
function pg(){return document.getElementById('mealPackPage')}function bd(){return document.getElementById('mealPackBody')}
function opt(v){return ms().map(x=>`<option ${x===v?'selected':''}>${e(x)}</option>`).join('')}
function show(t,h){document.getElementById('mealPackTitle').textContent=t;bd().innerHTML=h;pg().classList.remove('hide')}
function install(){if(document.getElementById('mealPackPage'))return;let s=document.createElement('style');s.id='v574style';s.textContent=C;document.head.appendChild(s);let x=document.createElement('div');x.id='mealPackPage';x.className='fullpage hide';x.innerHTML=`<div class="fullpage-head"><button class="btn-ghost" onclick="mpBack()">← Back</button><b id="mealPackTitle">Meal Packs</b><button class="btn-ghost" onclick="closeMealPacks()">✕</button></div><div id="mealPackBody" class="fullpage-body"></div>`;document.body.appendChild(x)}
function tile(){let g=document.querySelector('#quickLog .quicklog-grid');if(!g)return;let b=document.getElementById('quickMealPacksBtn');if(!b){b=document.createElement('button');b.id='quickMealPacksBtn';b.className='quick-action';b.onclick=openMealPacks;g.appendChild(b)}let n=rd().length;b.innerHTML=`<span class="qa-icon">▣</span><strong>Meal packs</strong><span>${n?n+' saved · log a routine meal fast':'Save a meal once, then log it in seconds.'}</span>`}
function decor(){let a=[];try{a=log}catch{return}document.querySelectorAll('#meals .meal[data-meal]').forEach(c=>{let m=c.dataset.meal,n=a.filter(x=>x.meal===m),r=c.querySelector('.mp-tools');if(!n.length){r?.remove();return}if(!r){r=document.createElement('div');r.className='mp-tools';c.querySelector('.meal-hd')?.insertAdjacentElement('afterend',r)}r.innerHTML=`<button onclick="saveMealAsPack('${e(m)}')">▣ Save as pack</button>${rd().length?`<button onclick="choosePackToUpdate('${e(m)}')">Update pack</button>`:''}`})}
function list(){S={m:'list'};let a=rd().sort((x,y)=>(y.lastUsedAt||y.updatedAt||0)-(x.lastUsedAt||x.updatedAt||0));let h=`<div class="mpr" style="justify-content:space-between;margin-bottom:12px"><div><div class="sub">Reusable food shortcuts</div><h3 style="margin-top:2px">Meal Packs</h3></div><button class="mpg" onclick="newMealPack()">+ New</button></div>`;h+=a.length?a.map(p=>{let t=tot(p.items||[]);return`<div class="mpc"><div class="mpn">${e(p.name)}</div><div class="mpm">${e(p.defaultMeal)} · ${p.items.length} items · ${Math.round(t.c)} cal · ${Math.round(t.p)}g protein</div><div class="mpi">${e(p.items.slice(0,3).map(x=>x.name).join(' · '))}${p.items.length>3?' · +'+(p.items.length-3)+' more':''}</div><div class="mpr"><button class="mpb" onclick="reviewMealPack('${p.id}')">Log</button><button class="mpg" onclick="editMealPack('${p.id}')">Edit</button><button class="mpq" onclick="duplicateMealPack('${p.id}')">Duplicate</button><button class="mpd" onclick="deleteMealPack('${p.id}')">Delete</button></div></div>`}).join(''):`<div class="mpc"><b>No meal packs yet</b><div class="mpm">Log a meal on Today, then tap Save as pack.</div></div>`;show('Meal Packs',h)}
function review(){let p=gp(S.id),a=S.items.filter(x=>x.on),t=tot(a);show('Log meal pack',`<div class="sub">${e(p.name)}</div><h3 style="margin:3px 0 10px">Adjust today if needed.</h3><div class="mpc"><div class="mpm">Changes here apply only to this log unless you tap Update saved pack.</div></div><div class="mpf"><label class="sub">Log into meal</label><select onchange="mpTarget(this.value)">${opt(S.meal)}</select></div>${S.items.map((x,i)=>`<div class="mpc mpx"><input type="checkbox" ${x.on?'checked':''} onchange="mpOn(${i},this.checked)"><div><div class="mpn" style="font-size:13px">${e(x.name)}</div><div class="mpm">${Math.round(x.cal)} cal · ${Math.round(x.protein)}g protein / serving</div></div><div class="mps"><button onclick="mpQty(${i},-.25)">−</button><span class="mpt">${x.qty}×</span><button onclick="mpQty(${i},.25)">+</button></div></div>`).join('')}<div class="mpr" style="justify-content:space-between"><b>${Math.round(t.c)} cal · ${Math.round(t.p)}g protein</b><span class="sub">${a.length} selected</span></div><div class="mpr" style="margin-top:14px"><button class="mpb" onclick="logMealPackNow()">Log pack</button><button class="mpg" onclick="updatePackFromReview()">Update saved pack</button><button class="mpq" onclick="editMealPack('${p.id}')">Edit pack</button></div>`)}
function sync(){if(S?.m!=='edit')return;let n=document.getElementById('mpName'),m=document.getElementById('mpMeal');if(n)S.name=n.value;if(m)S.meal=m.value;document.querySelectorAll('.mpEq').forEach((q,i)=>{if(S.items[i])S.items[i].qty=Math.max(.25,Math.min(10,+q.value||1))})}
function edit(){show(S.id?'Edit meal pack':'New meal pack',`<div class="mpf"><input id="mpName" value="${e(S.name)}" placeholder="Pack name"><select id="mpMeal">${opt(S.meal)}</select></div><div class="mpc"><b>Foods</b><div class="mpm">Edit quantities, remove foods, or add another food below.</div>${S.items.length?S.items.map((x,i)=>`<div class="mpit"><div><div class="mpn" style="font-size:13px">${e(x.name)}</div><div class="mpm">${Math.round(x.cal)} cal · ${Math.round(x.protein)}g</div></div><input class="mpEq" type="number" min=".25" max="10" step=".25" value="${x.qty}" onchange="mpEditQty(${i},this.value)"><button class="mpd" onclick="mpRemove(${i})">✕</button></div>`).join(''):'<div class="mpm" style="margin-top:9px">No foods yet.</div>'}<div style="margin-top:12px"><input id="mpSearch" placeholder="Add food…" oninput="mpSearchFood()"><div id="mpResults" class="mpres"></div></div></div>${S.id?`<button class="mpq" onclick="replacePackFromMeal()">↻ Replace from currently viewed ${e(S.meal)} meal</button>`:''}<div class="mpr" style="margin-top:13px"><button class="mpb" onclick="saveMealPackEditor()">Save pack</button><button class="mpq" onclick="openMealPacks()">Cancel</button></div>`)}
function search(){let q=(document.getElementById('mpSearch')?.value||'').toLowerCase().trim(),b=document.getElementById('mpResults');if(!b)return;if(!q){b.innerHTML='';return}let mine=[];try{mine=foods.filter(f=>f.name.toLowerCase().includes(q)).slice(0,8)}catch{}let db=[];try{let names=new Set(mine.map(x=>x.name));db=DB.filter(r=>r[0].toLowerCase().includes(q)&&!names.has(r[0])).slice(0,8)}catch{}b.innerHTML=mine.map(f=>`<button data-f="${e(f.id)}"><span>${e(f.name)}</span><small>${f.cal} cal · ${f.protein}g</small></button>`).join('')+db.map((r,i)=>`<button data-d="${i}"><span>${e(r[0])}</span><small>${r[1]} cal · ${r[2]}g</small></button>`).join('');b.querySelectorAll('[data-f]').forEach(x=>x.onclick=()=>{let f=foods.find(z=>String(z.id)===x.dataset.f);if(f)addEd(snap(f))});b.querySelectorAll('[data-d]').forEach(x=>x.onclick=()=>{let r=db[+x.dataset.d];if(r)addEd(snap({name:r[0],cal:r[1],protein:r[2],qty:1}))})}
function addEd(x){sync();S.items.push(x);edit()}
window.openMealPacks=function(){try{closeQuickLog()}catch{}list()};window.closeMealPacks=function(){pg().classList.add('hide');S=null};window.mpBack=function(){if(!S||S.m==='list')closeMealPacks();else list()};
window.reviewMealPack=function(x){let p=gp(x);if(!p)return;S={m:'review',id:x,meal:p.defaultMeal||'Other',items:p.items.map(z=>({...snap(z),on:true}))};review()};window.mpTarget=v=>S.meal=v;window.mpOn=(i,v)=>{S.items[i].on=v;review()};window.mpQty=(i,d)=>{S.items[i].qty=Math.max(.25,Math.min(10,Math.round((S.items[i].qty+d)*4)/4));review()};
window.logMealPackNow=function(){let p=gp(S.id),a=S.items.filter(x=>x.on),m=S.meal;if(!p||!a.length)return alert('Choose at least one food.');a.forEach(x=>{let q=mac(x.name,x.cal,x.protein,x.carbs,x.fat);log.push({id:uid(),name:x.name,cal:x.cal,protein:x.protein,carbs:q.carbs,fat:q.fat,qty:x.qty,meal:m,ts:Date.now(),mealPackId:p.id,mealPackName:p.name})});let z=rd(),i=z.findIndex(x=>x.id===p.id);if(i>=0)z[i].lastUsedAt=Date.now();wr(z);persistLog();closeMealPacks();showTab('today');setTimeout(()=>document.querySelector(`[data-meal="${m}"]`)?.scrollIntoView({behavior:'smooth',block:'center'}),60)};
window.updatePackFromReview=function(){let p=gp(S.id),a=S.items.filter(x=>x.on).map(snap);if(!p||!a.length)return;if(confirm(`Update “${p.name}” with these foods, quantities, and ${S.meal} as its default meal?`)){put({...p,defaultMeal:S.meal,items:a,updatedAt:Date.now()});review()}};
window.editMealPack=function(x){let p=gp(x);if(!p)return;S={m:'edit',id:x,name:p.name,meal:p.defaultMeal||'Other',items:p.items.map(snap),createdAt:p.createdAt||Date.now()};edit()};window.newMealPack=function(){S={m:'edit',id:null,name:'',meal:(typeof guessMeal==='function'?guessMeal():'Other'),items:[],createdAt:Date.now()};edit()};window.saveMealAsPack=function(m){let a=mi(m);if(!a.length)return;S={m:'edit',id:null,name:m+' pack',meal:m,items:a,createdAt:Date.now()};edit()};
window.saveMealPackEditor=function(){sync();let n=S.name.trim();if(!n)return alert('Give this meal pack a name.');if(!S.items.length)return alert('Add at least one food.');let old=S.id?gp(S.id):null;put({id:S.id||id(),name:n,defaultMeal:S.meal,items:S.items.map(snap),createdAt:old?.createdAt||S.createdAt||Date.now(),updatedAt:Date.now(),lastUsedAt:old?.lastUsedAt||0});list()};window.mpEditQty=(i,v)=>S.items[i].qty=Math.max(.25,Math.min(10,+v||1));window.mpRemove=function(i){sync();S.items.splice(i,1);edit()};window.mpSearchFood=search;
window.choosePackToUpdate=function(m){let a=mi(m);if(!a.length)return;let p=rd();if(!p.length)return saveMealAsPack(m);S={m:'pick',meal:m};show('Update meal pack',`<div class="mpc"><div class="mpm">Replace a saved pack with the foods currently logged in ${e(m)}. Historical logs stay unchanged.</div></div>${p.map(x=>`<button class="mpc" style="width:100%;text-align:left;color:var(--text)" onclick="updatePackFromMeal('${x.id}','${e(m)}')"><div class="mpn">${e(x.name)}</div><div class="mpm">${e(x.defaultMeal)} · ${x.items.length} items</div></button>`).join('')}`)};window.updatePackFromMeal=function(x,m){let p=gp(x),a=mi(m);if(p&&a.length&&confirm(`Replace “${p.name}” with the ${a.length} items in ${m}?`)){put({...p,defaultMeal:m,items:a,updatedAt:Date.now()});list()}};
window.replacePackFromMeal=function(){sync();let a=mi(S.meal);if(!a.length)return alert(`No foods are logged in ${S.meal} on the viewed day.`);if(confirm(`Replace this pack's foods with the ${a.length} items in ${S.meal}?`)){S.items=a;edit()}};window.duplicateMealPack=function(x){let p=gp(x);if(p){put({...p,id:id(),name:p.name+' copy',createdAt:Date.now(),updatedAt:Date.now(),lastUsedAt:0});list()}};window.deleteMealPack=function(x){let p=gp(x);if(p&&confirm(`Delete “${p.name}”? Historical food logs will stay unchanged.`)){wr(rd().filter(z=>z.id!==x));list()}};
function boot(){install();tile();let oq=window.openQuickLog;if(typeof oq==='function'&&!oq.__mp){let f=function(){tile();return oq.apply(this,arguments)};f.__mp=1;window.openQuickLog=f}let rm=window.renderMeals;if(typeof rm==='function'&&!rm.__mp){let f=function(){let r=rm.apply(this,arguments);setTimeout(decor,0);return r};f.__mp=1;window.renderMeals=f}setTimeout(decor,0);document.documentElement.dataset.thalifyTwaFeatureRelease=V}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(boot,0));else setTimeout(boot,0);
})();
